const express = require("express");
const router = express.Router();

const data = require("../data");
const getAPetData = data.getAPetData;

const path = require("path");

// GET http://localhost:3000/
router.get("/", async (req, res) => {
  try {
    res.status(200).render("homepage");
  } catch (e) {
    res.status(500).json({ message: e });
  }
});

router.get("/login", async (req, res) => {
  res.status(200).render("login");
});

router.get("/signup/sr", async (req, res) => {
  res.status(200).render("shelter&rescueSignup");
});

router.post("/signup/sr", async (req, res) => {
  try {
    const signupData = req.body;

    if (signupData.profilePicture === undefined) {
      throw {
        status: 400,
        error:
          "Profile Picture public URL not passed - Generated by '/routes/getAPetApi.js'.",
      };
    }

    if (signupData.name === undefined) {
      throw {
        status: 400,
        error:
          "Shelter/Rescue name not passed - Generated by '/routes/getAPetApi.js'.",
      };
    }

    if (signupData.email === undefined) {
      throw {
        status: 400,
        error: "E-Mail not passed - Generated by '/routes/getAPetApi.js'.",
      };
    }

    if (signupData.password === undefined) {
      throw {
        status: 400,
        error: "Password not passed - Generated by '/routes/getAPetApi.js'.",
      };
    }

    if (signupData.state === undefined) {
      throw {
        status: 400,
        error:
          "Location State not passed - Generated by '/routes/getAPetApi.js'.",
      };
    }

    if (signupData.city === undefined) {
      throw {
        status: 400,
        error:
          "Location City not passed - Generated by '/routes/getAPetApi.js'.",
      };
    }

    if (signupData.biography === undefined) {
      throw {
        status: 400,
        error: "Biography not passed - Generated by '/routes/getAPetApi.js'.",
      };
    }

    if (signupData.phoneNumber === undefined) {
      throw {
        status: 400,
        error:
          "Phone Number not passed - Generated by '/routes/getAPetApi.js'.",
      };
    }

    if (signupData.website === undefined) {
      throw {
        status: 400,
        error: "Website URL not passed - Generated by '/routes/getAPetApi.js'.",
      };
    }

    if (signupData.socialMedia === undefined) {
      throw {
        status: 400,
        error:
          "Social Media URL not passed - Generated by '/routes/getAPetApi.js'.",
      };
    }
  } catch (e) {
    res.status(e.status).send({ error: e.error, title: "Error" });
    return;
  }

  try {
    const signupData = req.body;

    const newSrUser = await getAPetData.addSr(signupData);
    res.redirect("/");
  } catch (e) {
    res.status(e.status).json({ error: e.error });
  }
});

router.get("/signup/popa", async (req, res) => {
  res.status(200).render("petOwner&petAdopterSignup");
});

router.post("/signup/popa", async (req, res) => {
  try {
    const signupData = req.body;

    if (signupData.profilePicture === undefined) {
      throw {
        status: 400,
        error:
          "Profile Picture public URL not passed - Generated by '/routes/getAPetApi.js'.",
      };
    }

    if (signupData.fname === undefined) {
      throw {
        status: 400,
        error: "First name not passed - Generated by '/routes/getAPetApi.js'.",
      };
    }

    if (signupData.lname === undefined) {
      throw {
        status: 400,
        error: "Last name not passed - Generated by '/routes/getAPetApi.js'.",
      };
    }

    if (signupData.email === undefined) {
      throw {
        status: 400,
        error: "E-Mail not passed - Generated by '/routes/getAPetApi.js'.",
      };
    }

    if (signupData.password === undefined) {
      throw {
        status: 400,
        error: "Password not passed - Generated by '/routes/getAPetApi.js'.",
      };
    }

    if (signupData.phoneNumber === undefined) {
      throw {
        status: 400,
        error:
          "Phone Number not passed - Generated by '/routes/getAPetApi.js'.",
      };
    }
    if (signupData.zipCode === undefined) {
      throw {
        status: 400,
        error: "Zip Code not passed - Generated by '/routes/getAPetApi.js'.",
      };
    }

    if (signupData.biography === undefined) {
      throw {
        status: 400,
        error: "Biography not passed - Generated by '/routes/getAPetApi.js'.",
      };
    }

    if (signupData.dateOfBirth === undefined) {
      throw {
        status: 400,
        error: "DOB not passed - Generated by '/routes/getAPetApi.js'.",
      };
    }
  } catch (e) {
    res.status(e.status).send({ error: e.error, title: "Error" });
    return;
  }

  try {
    const signupData = req.body;
    const newPoPa = await getAPetData.addPoPa(signupData);
    res.redirect("/");
  } catch (e) {
    res.status(e.status).json({ error: e.error });
  }
});
module.exports = router;
